### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by AK391** [xinntao/Real-ESRGAN#1]
Hi can you please add a google colab for inference

**Comment by YiWeiHuang-stack** [comment]
https://colab.research.google.com/drive/1YhN4UA9gunHwpKKfy1XvfSWV_4430ZBy?usp=sharing

**Comment by xinntao** [comment]
@AK391  We have provided a colab demo in https://colab.research.google.com/drive/1k2Zod6kSHEvraybHl50Lys0LerhyTMCo?usp=sharing

@YiWeiHuang-stack Thanks, we also provide a colab demo, which  may be more convenient.

**Comment by AK391** [comment]
@xinntao thanks, is it possible to due inference on cpu on colab?

**Comment by xinntao** [comment]
@AK391 It supports CPU on colab, but 1) it is much slower than GPU; 2) you may need to use the `--tile` option to avoid memory issues. 

You can also try the portable executable file on Windows: https://github.com/xinntao/Real-ESRGAN#Portable-executable-files
