### ISSUE TITLE
multi gpu training error

### ISSUE THREAD

**Issue by splinter21** [xinntao/Real-ESRGAN#100]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 8665) of binary: xxxxxx/anaconda3/envs/esr/bin/python

CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=4321 realesrgan/train.py -opt xxx --launcher pytorch --auto_resume

**Comment by xinntao** [comment]
Can you provide more info?

It seems it's an issue of your installed pytorch.
