### ISSUE TITLE
weird error message, if the output directory doesn't exist 

### ISSUE THREAD

**Issue by eps696** [xinntao/Real-ESRGAN#11]
hi, thanks for this cool tool.
when runnning windows executable against existing input directory (but without existing output one), it fails with the message: `invalid outputpath extension type`. it's not a big deal to create output directory beforehand manually, but it really took a while to understand first time what was the actual problem. 
it would be very helpful either to change that message to something more meaningful, or (better) to add output directory auto-creation.

**Comment by xinntao** [comment]
Thanks for your feedback. I will fix it later. 😄

**Comment by xinntao** [comment]
@eps696 
I have fixed it. The new release will create the folder if it does exist.

See https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.1.2

**Comment by aramrw** [comment]
just tried, this still happens on windows 11

**Comment by Zejin-Liu2022** [comment]
> just tried, this still happens on windows 11

i had just run into the same problem on Windows 11. I wonder if you had already sloved the problem?
