### ISSUE TITLE
Can you release the source code of the implementation using ncnn platform???

### ISSUE THREAD

**Issue by sangjinhong** [xinntao/Real-ESRGAN#129]
Can you release the source code of the implementation using ncnn platform???

**Comment by xinntao** [comment]
The codes for ncnn is here： https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan


*Real-ESRGAN ncnn Vulkan* heavily borrows from [realsr-ncnn-vulkan](https://github.com/nihui/realsr-ncnn-vulkan).
Many thanks to [nihui](https://github.com/nihui), [ncnn](https://github.com/Tencent/ncnn) and [realsr-ncnn-vulkan](https://github.com/nihui/realsr-ncnn-vulkan)

**Comment by sangjinhong** [comment]
thanks very much !!!

2021년 10월 16일 (토) 오후 5:22, Xintao ***@***.***>님이 작성:
