### ISSUE TITLE
ImportError: cannot import name 'circular_lowpass_kernel' from 'basicsr.data.degradations' 

### ISSUE THREAD

**Issue by mohammadmardani** [xinntao/Real-ESRGAN#15]
I am trying to train on my own dataset.
encounter this error:
ImportError: cannot import name 'circular_lowpass_kernel' from 'basicsr.data.degradations' 

I am using basicsr 1.3.3.3

**Comment by woctezuma** [comment]
Upgrade to 1.3.3.10.

https://github.com/xinntao/BasicSR/commit/798ca1e654df4382db263fa59ed936ac3cf2bd6d
