### ISSUE TITLE
Training Problem about GAN

### ISSUE THREAD

**Issue by YangGangZhiQi** [xinntao/Real-ESRGAN#16]
Hi,
     Great works!  I am reproducing your works. When training real-ESRGAN model, the pictures generated  are even more blur than generated by real-ESRNET. Have you ever encountered this problem?

**Comment by xinntao** [comment]
Did you fine-tune it from the Real-ESRNet?

Also, check whether the codes are the latest.

**Comment by YangGangZhiQi** [comment]
@xinntao Thinks for your quick reply! Yes. I fine-tune it from the real-ESRNet trained myself. My current iteration step is 20000, is my training Iteration not enough? 
Ok , I will check my codes.

**Comment by xinntao** [comment]
It is strange. I will also train it to see whether it has bugs ~

**Comment by xinntao** [comment]
@YangGangZhiQi  
I have tested with the current Real-ESRGAN repo, and I could achieve a similar visual performance as the released model. 

You may check your codes and settings.
