### ISSUE TITLE
Colab is not working atm

### ISSUE THREAD

**Issue by Dertrs** [xinntao/Real-ESRGAN#167]
Hello since a few hours, colab does not work. and I get this error. (it has always worked fine).

Traceback (most recent call last):
  File "inference_realesrgan.py", line 7, in <module>
    from realesrgan import RealESRGANer
  File "/content/Real-ESRGAN/realesrgan/__init__.py", line 5, in <module>
    from .utils import *
  File "/content/Real-ESRGAN/realesrgan/utils.py", line 7, in <module>
    from basicsr.utils.download_util import load_file_from_url
ImportError: cannot import name 'load_file_from_url' from 'basicsr.utils.download_util' (/usr/local/lib/python3.7/dist-packages/basicsr/utils/download_util.py)

**Comment by terekita** [comment]
here's a temporary fix: 
replace !pip install basicsr with this in your notebook !pip install git+https://github.com/xinntao/BasicSR.git

**Comment by Dertrs** [comment]
> here's a temporary fix: replace !pip install basicsr with this in your notebook !pip install git+https://github.com/xinntao/BasicSR.git

Thank you for the tip.
