### ISSUE TITLE
The model generates weird artifacts

### ISSUE THREAD

**Issue by AChen-qaq** [xinntao/Real-ESRGAN#174]
![image](https://user-images.githubusercontent.com/61538940/144851479-04242ce4-92f6-46fb-b038-34593e29e079.png)
![image](https://user-images.githubusercontent.com/61538940/144851532-f723b790-16c3-4f93-b3e1-93bc81b56cef.png)

And here is the raw input image:
![QQ图片20211206202834](https://user-images.githubusercontent.com/61538940/144851632-55eb4fd9-acb9-4a47-8e77-f360c0c38dde.png)

**Comment by xinntao** [comment]
For anime images/illustrations, please do not use `face_enhance` option
