### ISSUE TITLE
Error related to File/Video Import Widget

### ISSUE THREAD

**Issue by Ghee36** [xinntao/Real-ESRGAN#19]
MessageError                              Traceback (most recent call last)
<ipython-input-2-3dd1eb078770> in <module>()
     14 
     15 # upload images
---> 16 uploaded = files.upload()
     17 for filename in uploaded.keys():
     18   dst_path = os.path.join(upload_folder, filename)

2 frames
/usr/local/lib/python3.7/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
    104         reply.get('colab_msg_id') == message_id):
    105       if 'error' in reply:
--> 106         raise MessageError(reply['error'])
    107       return reply.get('data', None)
    108 

MessageError: TypeError: Cannot read property '_uploadFiles' of undefined

**Comment by xinntao** [comment]
It seems it is an issue of colab, not related to real-esrgan~

**Comment by Ghee36** [comment]
You are correct.  It was a cookie related issue.

In the same runtime it is now providing this error in the colab notebook.

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-a16867ab1a8a> in <module>()
      4   os.remove(zip_filename)
      5 os.system(f"zip -r -j {zip_filename} results/*")
----> 6 files.download(zip_filename)

/usr/local/lib/python3.7/dist-packages/google/colab/files.py in download(filename)
    141       raise OSError(msg)
    142     else:
--> 143       raise FileNotFoundError(msg)  # pylint: disable=undefined-variable
    144 
    145   comm_manager = _IPython.get_ipython().kernel.comm_manager

FileNotFoundError: Cannot find file: Real-ESRGAN_result.zip

Something missing?

**Comment by xinntao** [comment]
the codes will zip a file，it seems that you have not zipped the file.  It may also be the colab issue~





Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ghee36** [comment]
I am using an unmodified version of the colab notebook.  Which cell does the codes zip a file so I can double check?  Thanks!

**Comment by xinntao** [comment]
The last cell `os.system(f"zip -r -j {zip_filename} results/*")`

**Comment by Ghee36** [comment]
ModuleNotFoundError: No module named 'realesrgan.version'

is appearing prior to the last cell.  Is this remedied by running the last cell first?

**Comment by xinntao** [comment]
I have just the codes several minutes ago. 
Please use the latest colab demo: https://colab.research.google.com/drive/1k2Zod6kSHEvraybHl50Lys0LerhyTMCo?usp=sharing

**Comment by t-qureshi** [comment]
For me, it works against;

`python setup.py install`

I am setting up this locally.
