### ISSUE TITLE
x2超分

### ISSUE THREAD

**Issue by sunyclj** [xinntao/Real-ESRGAN#196]
您好，使用您开源的超分模型RealESRGAN_x4plus.pth，修改outscale，进行x2测试，占用的显存与x4超分相同，推理时间比x4稍长；根据您文中对pixel-unshuffle的描述，x2的推理时间和显存占用不应该是会降低吗？

**Comment by jorjiang** [comment]
你要用2x的模型 一样的网络 当然花的时间和内存是一样的
