### ISSUE TITLE
'VCOMP140D.DLL' is required

### ISSUE THREAD

**Issue by cyso1988** [xinntao/Real-ESRGAN#2]
A straightforward execution of the 'Windows executable files' fails because 'VCOMP140D.DLL' is required.

For me it was necessary to install 'Visual Studio 2019' and load the 'MSVC v142' package to solve this problem.
Putting the 'VCOMP140D.DLL' into the 'Windows executable files' would help other users.

The result look good, thanks for releasing.

**Comment by xinntao** [comment]
@cyso1988 Thanks for reporting the issue.

I am not familiar with the windows dll mechanism. Is it OK to just put any version of 'VCOMP140D.DLL' inside the 'Windows executable files'?

I have tried the 'Windows executable files' on both of my laptops (one has installed Visual Studio 2019, the other has not installed). Both do not encounter this issue.  So I can't verify the above solution.

**Comment by cyso1988** [comment]
Nihui also ships a "VCOMP140.DLL" in his Windows version of "waifu2x-ncnn-vulkan". 
Copy your "VCOMP140D.DLL" which you find in "x:\Windows\System32" into the package.

**Comment by xinntao** [comment]
@cyso1988  Thank your for the information 😃 :

**Comment by xinntao** [comment]
I have updated a new version, you may check whether it is ok~ 

https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.1/RealESRGAN-ncnn-vulkan-20210725-windows.zip

**Comment by cyso1988** [comment]
Works flawlessly. Thanks.

Why did you take out TTA? In my eyes, it had a right to exist. Q.Q
Did some tests the last few hours and in some cases it was quite useful.

**Comment by xinntao** [comment]
Thanks ;-)

I think TTA takes too much time=-= 
According to your experiences, if it's quite useful for some cases, I will put it back in the next version.

**Comment by xinntao** [comment]
@cyso1988 
I have added the `tta` option back.

See https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.1.2
