### ISSUE TITLE
图片图块排版不正确，请修复

### ISSUE THREAD

**Issue by cuihua0** [xinntao/Real-ESRGAN#203]
我使用windows的版本，程序目录下自带的input.jpg测试，使用的指令如下
D:\Real-ESRGAN-realesrgan-ncnn-vulkan-20211212-windows\realesrgan-ncnn-vulkan.exe -i input.jpg -o test.png -s 2
D:\Real-ESRGAN-realesrgan-ncnn-vulkan-20211212-windows\realesrgan-ncnn-vulkan.exe -i input.jpg -o test.png -s 1
分别测试了1倍数和2倍数，都是这样的排版，请修复

![test](https://user-images.githubusercontent.com/49671528/147400819-7d5d0bcc-f336-43f3-b0b3-6543da33b367.png)

**Comment by cuihua0** [comment]
看起来这像是tile大小的问题，我使用最小的默认32放大就会出现这种情况，我使用其他的一些图片都有这种情况出现

**Comment by AaronFeng753** [comment]
模型问题，默认模型是4x的，这个命令行程序不支持resize，所以你只能用4倍数放大才能正常生成图片

你也可以用我做的GUI：https://github.com/AaronFeng753/Waifu2x-Extension-GUI

**Comment by cuihua0** [comment]
确实，我试了很多图片了。我等会试试你这个。他介绍里面说可以resize 1倍数2倍数....，然而实际是这样

**Comment by AaronFeng753** [comment]
> 确实，我试了很多图片了。我等会试试你这个。他介绍里面说可以resize 1倍数2倍数....，然而实际是这样

他说的4倍和2倍指里面有原生支持2倍的模型和4倍的模型，但这俩不是一个模型，也不是默认的，1倍我倒是没看到他说，总之需要手动指定模型才能实现2x和4x切换。如果您用我的gui就可以免去这些麻烦

**Comment by cuihua0** [comment]
> > 确实，我试了很多图片了。我等会试试你这个。他介绍里面说可以resize 1倍数2倍数....，然而实际是这样
> 
> 他说的4倍和2倍指里面有原生支持2倍的模型和4倍的模型，但这俩不是一个模型，也不是默认的，1倍我倒是没看到他说，总之需要手动指定模型才能实现2x和4x切换。如果您用我的gui就可以免去这些麻烦

好的，谢谢

**Comment by kodxana** [comment]
The scale settings are broken for now and if you want scale x2 you need x2 model and x4 model for x4 scale.
