### ISSUE TITLE
2.3.0 won't work on older distros (and Google Colab)

### ISSUE THREAD

**Issue by Ednaordinary** [xinntao/Real-ESRGAN#204]
Version 2.3.0 requires the library GLIBC version 2.29, but older distros and Google Colab have older versions that aren't supported by esrgan. The fix is to downgrade to version 2.2.4, but this means older distros must use an older version, which isn't a concern for most users, but it also means Google Colab cannot use newer versions than 2.2.4

**Comment by kodxana** [comment]
Issue is that NCNN implementation now uses glslangValidator package that requires GLIBC version 2.29+.
I have tried to compile it directly on colab but without luck. What I will try is to build glslangValidator on colab and then build Resergan-ncnn with custom glslangValidator binary. That should allow to run new version on older glibc version.

**Comment by kodxana** [comment]
Note the PyTorch implementation works fine.

**Comment by kodxana** [comment]
@Ednaordinary I managed to get it working. Builded binary file on Ubuntu 16.04 docker to make it work :)
[realesrgan-ncnn-vulkan-colab.zip](https://github.com/xinntao/Real-ESRGAN/files/7864973/realesrgan-ncnn-vulkan-colab.zip)

You might need run
```!chmod +x realesrgan-ncnn-vulkan-colab```

**Comment by Ednaordinary** [comment]
> @Ednaordinary I managed to get it working. Builded binary file on Ubuntu 16.04 docker to make it work :)
> [realesrgan-ncnn-vulkan-colab.zip](https://github.com/xinntao/Real-ESRGAN/files/7864973/realesrgan-ncnn-vulkan-colab.zip)
> 
> You might need run
> ```!chmod +x realesrgan-ncnn-vulkan-colab```
> 
> 

Oh nice! Should be useful for some of my notebooks

**Comment by darkcristle** [comment]
Hi, first off thanks so much for making this @kodxana, however I am receiving this error "find_blob_index_by_name data failed" after every log entry.  All out frames are solid black.  

Any help is appreciated, thanks.

**Comment by kodxana** [comment]
@darkcristle Did you created models folder and uploaded model files there?

**Comment by darkcristle** [comment]
@kodxana Yup, they are from the most recent release.  Executable is in the same folder as the Model folder.

**Comment by kodxana** [comment]
It should be:

executable file
models folder
 - modelname.bin
 - modelname.param

**Comment by darkcristle** [comment]
This is my folder layout.  I believe it is correct.

![image](https://user-images.githubusercontent.com/85809726/151674068-516962e1-f258-4651-9672-9ec4b40cc809.png)

![image](https://user-images.githubusercontent.com/85809726/151674091-3fb07646-4611-4004-9ba2-17021838d0ce.png)

**Comment by kodxana** [comment]
I think it should be models not Models

**Comment by darkcristle** [comment]
@kodxana yes that worked.  Thank you very much.  Now the real struggle is hoping to get a good GPU lol.

**Comment by Snowblind350** [comment]
@kodxana 

[Real-ESRGAN v0.3.0](https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.3.0) requires the library GLIBC version 2.29 as well. 

Would you please build a new binary file for Google Colab use?

Thank you!

**Comment by Ednaordinary** [comment]
(didn't mean to keep this open)
