### ISSUE TITLE
Can I develop a GUI for this?

### ISSUE THREAD

**Issue by AaronFeng753** [xinntao/Real-ESRGAN#21]
Hi, I am the developer of Waifu2x-Extension-GUI

I wonder if I can add Real-Esrgan support to my GUI, since your project does not have a license, I think I should ask for your permission first

Waifu2x-Extension-GUI:
https://github.com/AaronFeng753/Waifu2x-Extension-GUI

**Comment by AaronFeng753** [comment]
抱歉, 我一时眼瞎没看见根目录里的license, 抱歉打扰了

**Comment by xinntao** [comment]
😄
