### ISSUE TITLE
Seams after upscaling

### ISSUE THREAD

**Issue by Matteoki** [xinntao/Real-ESRGAN#211]
Whenever i input a seamless image i get an image with seams all around the edges, is there a way to patch the seams?

**Comment by owlsoul0** [comment]
Having the same issue, I think it is because the model breaks down the image into less memory-hungry patches before processing them but I don't know how to fix it.

**Comment by owlsoul0** [comment]
After trying a few things, changing the tile size to a considerable amount seems to work and make the seams less frequent, but it doesn't eliminate them completely and depending on the memory your setup has it may not be possible...

**Comment by Alhasan-Abdellatif** [comment]
I have implemented a local padding technique that super-resolved large inputs without introducing seaming artifacts, https://github.com/Alhasan-Abdellatif/Real-ESRGAN-lp
