### ISSUE TITLE
使用示例，可以输出处理过的图片，但视频不行

### ISSUE THREAD

**Issue by A1exan10er** [xinntao/Real-ESRGAN#216]
cmd具体显示如下，请问是否是与其他包发生冲突？

Testing 0 00003
Testing 1 0014
Testing 2 0030
Testing 3 ADE_val_00000114
Testing 4 OST_009
Testing 5 tree_alpha_16bit
        Input is a 16-bit image
Testing 6 video
[ WARN:0@9.333] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('inputs\video'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "D:\Universitaet\GitHub\Real-ESRGAN\inference_realesrgan.py", line 128, in <module>
    main()
  File "D:\Universitaet\GitHub\Real-ESRGAN\inference_realesrgan.py", line 103, in main
    if len(img.shape) == 3 and img.shape[2] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by mikessb** [comment]
视频使用inference_realesrgan_video.py和对应模型，并指定视频文件名称，不要使用文件夹

**Comment by msjie1** [comment]
> 视频使用inference_realesrgan_video.py和对应模型，并指定视频文件名称，不要使用文件夹

我指定了文件名称报这个错误,怎么解决?
  File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 201, in <module>
    main()
  File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 110, in main
    if mimetypes.guess_type(args.input)[0].startswith('videos'):  # is a video file
AttributeError: 'NoneType' object has no attribute 'startswith'
我的视频名称是videos,放到了../inputs/video的文件目录下!

**Comment by matcxf** [comment]
@msjie1 使用以下命令即可：
`python inference_realesrgan_video.py -n RealESRGANv2-animevideo-xsx4 -i inputs\video\onepiece_demo.mp4`

**Comment by matcxf** [comment]
但输出的是每一帧的图片:(

**Comment by NoirJ0e** [comment]
> 但输出的是每一帧的图片:(

加上 `-a -v` 这两个参数就可以输出视频了，还带有原视频的音轨

**Comment by LL223851** [comment]
灰度图片也报错

**Comment by AIhasArrived** [comment]
Could someone translate the solution for me in english  ? @A1exan10er  @LL223851  @Matrix-Chan @NoirJ0e @tangze-Asuka 
please? thanks

**Comment by tangze-Asuka** [comment]
> 有人可以用英语为我翻译解决方案吗？ 请？谢谢

mikessb: for video use reference_realesrgan_video.py and the corresponding model and specify the video file name, don't use the folder
tangze-Asuka. 
I specified the file name and got this error, how can I fix it?
File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 201, in
main()
File "E:\Typora\Real-ESRGAN-master\inference_realesrgan_video.py", line 110, in main
if mimetypes.guess_type(args.input)[0].startswith('videos'): # is a video file
AttributeError: 'NoneType' object has no attribute 'startswith'
The name of my video is videos, and it's in... /inputs/video!
@tangze-Asuka: Just use the following command:
python inference_realesrgan_video.py -n RealESRGANv2-animevideo-xsx4 -i inputs\video\onepiece_demo.mp4
But the output is the image of each frame
NoirJ0e: With these two arguments you can output the video with the original audio track -a -v

Also please use Google Translate wisely!

**Comment by AIhasArrived** [comment]
@tangze-Asuka  thanks.
I have a question for you all.
What hardware (nvidia GPu etc) do you use?
And HOW MUCH TIME does it take for you to UPSCALE a 1 minute video?

I am using it with wave2lip_HD, but I am having problems, sometimes very costly GPU (out of memory) despite having a good card, sometimes it takes TOO MUCH LONG TIME, also do you know anything about lip Sync technologies? If you have any insight or suggestions? Thanks in advance.

**Comment by tangze-Asuka** [comment]
> @tangze-Asuka thanks. I have a question for you all. What hardware (nvidia GPu etc) do you use? And HOW MUCH TIME does it take for you to UPSCALE a 1 minute video?
> 
> I am using it with wave2lip_HD, but I am having problems, sometimes very costly GPU (out of memory) despite having a good card, sometimes it takes TOO MUCH LONG TIME, also do you know anything about lip Sync technologies? If you have any insight or suggestions? Thanks in advance.

  I'm using an RTX3050ti card, I don't have enough video memory to parse a one minute video, so I don't know how long it will take, plus it's hard for a PC to support this level of parsing, so use a server to parse long videos if you want a better experience!

**Comment by AIhasArrived** [comment]
What servers do you use, and how much does it cost you?
I did not know this was SO MUCH consuming GPU.. :(

**Comment by tangze-Asuka** [comment]
> What servers do you use, and how much does it cost you? I did not know this was SO MUCH consuming GPU.. :(

I use the school's server, so I can not give you rationalised advice, depending on the intensity of your use of deep learning, high-intensity use of deep learning to buy a better cloud server, occasional use of deep learning, then the personal computer can barely meet (RTX 3080 and above, graphics memory 8G, memory 32G).
