### ISSUE TITLE
Inference on cpu

### ISSUE THREAD

**Issue by alankras** [xinntao/Real-ESRGAN#22]
Hi! Really great project, but inference on cpu is very slow :( 
Any ideas how to speed it up? (probably deploy on openvino or something else)

**Comment by xinntao** [comment]
You may try this https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.2/realesrgan-ncnn-vulkan-20210801-windows.zip

**Comment by alankras** [comment]
Oh great, i will check it

**Comment by rthangam** [comment]
Any downloads for Mac ?

**Comment by linzzhu** [comment]
I have a same problem in Mac, can you check this? thanks
`python inference_gfpgan.py -i inputs/whole_imgs -o results -v 1.3 -s 2
inference_gfpgan.py:62: UserWarning: The unoptimized RealESRGAN is slow on CPU. We do not use it. If you really want to use it, please modify the corresponding codes.
  warnings.warn('The unoptimized RealESRGAN is slow on CPU. We do not use it. '
Traceback (most recent call last):
  File "inference_gfpgan.py", line 155, in <module>
    main()
  File "inference_gfpgan.py", line 101, in main
    raise ValueError(f'Model {model_name} does not exist.')`
