### ISSUE TITLE
Strange glitch?

### ISSUE THREAD

**Issue by AIisCool** [xinntao/Real-ESRGAN#220]
![image](https://user-images.githubusercontent.com/92149242/149468203-c94fd4a7-f3b3-47e0-8209-28a213aa496e.png)
Only happens when using the RealESRGAN_x4plus model, not RealESRGAN_x2plus.

**Comment by kodxana** [comment]
Could you give more details?

**Comment by AIisCool** [comment]
Think I figured it out. Seems it was a conflict with a filter I was using prior to upscaling.

**Comment by JensDA** [comment]
I'm encountering a similar glitch while finetuning the x2 model. May I ask what the filter conflict you had was?
