### ISSUE TITLE
I made a GUI with Video/Photo/GIF support

### ISSUE THREAD

**Issue by AaronFeng753** [xinntao/Real-ESRGAN#23]
Hello again, I am the developer of Waifu2x-Extension-GUI, and I just added RealESRGAN-NCNN-Vulkan support to my GUI in v3.80.01-beta update

So now we can use RealESRGAN-NCNN-Vulkan to process Video/Photo/GIF on a Windows PC with a user friendly GUI

Could you consider add my project page to the README? thanks

https://github.com/AaronFeng753/Waifu2x-Extension-GUI

![Snipaste_2021-08-09_19-51-42](https://user-images.githubusercontent.com/52553688/128701975-aa5d79a6-30eb-48d2-b833-0ea8534fbd79.jpg)

![Snipaste_2021-08-09_19-53-04](https://user-images.githubusercontent.com/52553688/128702070-98e7f24c-c986-4806-a836-60e978aea639.jpg)

**Comment by xinntao** [comment]
Thanks:-) You have done a good job for the community development.

Waifu2x-Extension-GUI has a Premium version, which can be used commercially. So, it may have some issues. 
I think you already have a great impact in the community 😄

**Comment by AaronFeng753** [comment]
thanks, I can understand your concern

**Comment by AaronFeng753** [comment]
And thank you for this awesome project, really looking forward to the 2x model update
