### ISSUE TITLE
Anyway to have the Pytorch version pull directly from extracted frames?

### ISSUE THREAD

**Issue by darkcristle** [xinntao/Real-ESRGAN#238]
Hello,

I am trying to run a colab instance and therefore am space limited.  I have gone ahead and extracted the frames on drive and deleted the source video to conserve space.

Is there a way I can point the inference at the "tmp_frames" folder directly rather than having it request a complete video?

Thanks.

**Comment by Juszoe** [comment]
I suggest you to use my modified code #213 which doesn't require temporary file
