### ISSUE TITLE
Is it possible to navitigate tmp_frames folder to drive/teamdrive?

### ISSUE THREAD

**Issue by jackthenewbie** [xinntao/Real-ESRGAN#239]
Just as the question said, I'm quickly out of storage. So I could only do 4m video at a time. I'm not sure if tmp_frames is the one that eat storage tho, sorry if I'm wrong. Doing it on google colab.

**Comment by kodxana** [comment]
You need edit this line to patch with folder you want temp files. Though it might slow down final rendering 
https://github.com/xinntao/Real-ESRGAN/blob/01aeba2f7ae859baf08c518c539d060a80e6c3db/inference_realesrgan_video.py#L110

**Comment by jackthenewbie** [comment]
> You need edit this line to patch with folder you want temp files. Though it might slow down final rendering
> 
> https://github.com/xinntao/Real-ESRGAN/blob/01aeba2f7ae859baf08c518c539d060a80e6c3db/inference_realesrgan_video.py#L110
When I mount my drive, and test out with demo, stuff is working. Thanks!

**Comment by jackthenewbie** [comment]
> You need edit this line to patch with folder you want temp files. Though it might slow down final rendering
> 
> https://github.com/xinntao/Real-ESRGAN/blob/01aeba2f7ae859baf08c518c539d060a80e6c3db/inference_realesrgan_video.py#L110

Sorry to open it again, so when I tried out `tmp_frames` with my 8m video, tmp_frames only eating around 8gb, which is not the large. `frames_tmpout` on the otherhand "may" be the one that eating storage, can I change the location of `frames_tmpout` like `tmp_frames` too?
