### ISSUE TITLE
Inconsistent default value of pre_pad argument

### ISSUE THREAD

**Issue by HolyWu** [xinntao/Real-ESRGAN#24]
The default value for `pre_pad` argument is inconsistent in https://github.com/xinntao/Real-ESRGAN/blob/fb3ff055e4b7e7268d0ad851a4b3eb314ba16932/inference_realesrgan.py#L23 and https://github.com/xinntao/Real-ESRGAN/blob/fb3ff055e4b7e7268d0ad851a4b3eb314ba16932/realesrgan/utils.py#L16.

Which one is preferred over the other? Thank you.

**Comment by xinntao** [comment]
@HolyWu 

I think it does not make many differences. 
In most cases, you can set it to 0. If you find there are some artifacts on borders, you can set it to 10 or a larger number.
