### ISSUE TITLE
有关评价指标

### ISSUE THREAD

**Issue by tongchangD** [xinntao/Real-ESRGAN#25]
未精读论文,

在论文后面贴了一些超分效果比较好的图片,请问这个方案在开源数据集上测试效果怎么样,比如 PSNR SSIM LPIPS 评估指标咋样

**Comment by xinntao** [comment]
1. PSNR, SSIM, LPIPS 是需要有 reference 图片的。针对实际场景的复原，很多时候没有reference/GT images， 所以不太适用。（一般会在synthetic上测试， 但这样其实不能很好反应实际场景的情况）
2. 图像质量的指标目前都只是侧面反应的，像PSNR，ssim都不能很好反应 人的视觉感受
3. 我们使用non-reference的NIQE做了测试，指标上会好。但是同样要注意，NIQE也是侧面的一个反映/参考，和人的视觉感受有差距。
![image](https://user-images.githubusercontent.com/17445847/128969825-0f972e3c-f0f1-478f-b76a-db897c7c9c99.png)

**Comment by tongchangD** [comment]
谢谢您的反馈

**Comment by gjd2017** [comment]
> 

那请问下在优化模型的时候，只能通过最后的推理效果来评估最优模型么？因为书面的指标不靠谱。
