### ISSUE TITLE
Audio sync issue on Apple Silicon

### ISSUE THREAD

**Issue by Waldo-ayy** [xinntao/Real-ESRGAN#253]
The video output is slower/higher (depending on the clip used) than the original audio, making it out of sync after just a couple of seconds. 
To compensate with this the last frame of the outputted video is stretched until the video is of the same length of the audio.

Any idea what's causing it or how it could be fixed?

EDIT: 
It looks as if even if I change the -r value to something other than 23.98FPS it still outputs at the same slower frame rate

**Comment by w2lf** [comment]
I have similar problem, and I am using vulcan version for windows. Tried a lot of things, nothing worked. Trying now vlc. basically I make video without audio and then add audio with vlc.
