### ISSUE TITLE
"Module Not Found" Google Colab

### ISSUE THREAD

**Issue by TFebbry** [xinntao/Real-ESRGAN#255]
I faced this problem in Google Colab, yesterday it still works. Are you experiencing the same problem?
![Problem](https://user-images.githubusercontent.com/99633413/153806917-5b4020e1-f174-4986-9450-51439fd0c731.PNG)

**Comment by xinntao** [comment]
I have fixed it. This issue is because I have just updated the GFPGAN repo: https://github.com/TencentARC/GFPGAN

If you still encounter the problem, you can reopen this issue.
Thanks :-)
