### ISSUE TITLE
DF2Kmultiscale+OST_sub

### ISSUE THREAD

**Issue by powder21** [xinntao/Real-ESRGAN#258]
Nice job! I have some questions about DF2Kmultiscale+OST_sub dataset.

1. Do you extract sub-image from OST dataset?
2. Do you downsample OST for multiscale?

**Comment by powder21** [comment]
for the 1st question, there are many images' resolution of OST smaller than the crop size 400, how do you deal with these small images?

**Comment by Lucien1996** [comment]
I also met the same problem. Could you tell me if you have solved this problem？
