### ISSUE TITLE
Local variable 'netscale' referenced before assignment

### ISSUE THREAD

**Issue by traderGoga** [xinntao/Real-ESRGAN#270]
Hello, thanks for a great job.
Unfortunately I have present error.
Is it a script error?

System:
docker run -it --gpus all nvidia/cuda:11.4.0-base-ubuntu20.04
Successfully installed all requirements, model, etc.
Python version 3.9.7
Anaconda version 1.9.0
Torch 1.10.2

Sincerely,
Vitalie 
![2022-03-05_11-47](https://user-images.githubusercontent.com/61839747/156878037-723f4f53-b5f8-496b-88d2-32140f3940da.png)

**Comment by traderGoga** [comment]
Resolved, it was my issue of placing model file.

**Comment by cjw19951005** [comment]
> Resolved, it was my issue of placing model file.

hwo to do that?

**Comment by traderGoga** [comment]
> hwo to do that?

try to place model files in different folders, I don`t remember right now which folder exactly, but it is or the same folder where you launch script, or other (always near the "project" folder)
