### ISSUE TITLE
ERROR : BrokenPipeError: [Errno 32] Broken pipe 

### ISSUE THREAD

**Issue by Lingxiang-Xu** [xinntao/Real-ESRGAN#274]
执行代码：python realesrgan/train.py -opt options/train_realesrgan_x4plus.yml --debug之后报错：
BrokenPipeError: [Errno 32] Broken pipe

**Comment by TangYuangao** [comment]
hi，could you tell me how to solve this problem? I meet this problem today.

**Comment by Lingxiang-Xu** [comment]
Maybe you can decrease your batch_size_per_gpu.
