### ISSUE TITLE
Anime Video Model introduces sharp edges where there previously were none

### ISSUE THREAD

**Issue by darkcristle** [xinntao/Real-ESRGAN#276]
I've noticed a reproducible bug in the model where it takes areas of the frame that may be best described as foggy, gaseous, or very dense geometric patterns and creates sharp edges around them.  

The most interesting part of this is that these edges may remain persistant.  

I.E. if the cloud or fog moves the sharp edge will remain in the same spot in the frame.   This is NOT the tiling issue caused by setting scale incorrectly.

![image](https://user-images.githubusercontent.com/85809726/157083910-848bb56b-1259-4dab-87b5-797a6ed91aa5.png) [Cropped Upscale]

![image](https://user-images.githubusercontent.com/85809726/157083983-bec52c67-9a5e-4eed-afef-01fe6cd2af85.png) [Cropped Source]

**Comment by ToTheBeginning** [comment]
Hi, we will soon release a new version of animevideo model (RealESRGAN-animevideov3-x4) which is able to avoid this kind of artifacts. Please stay tuned.

![](https://user-images.githubusercontent.com/11482921/164626342-04dd4083-b564-480f-a601-60c0dd989ca1.png)

**Comment by xinntao** [comment]
We have updated the RealESRGAN AnimeVideo-v3 model.

Please refer to 
https://github.com/xinntao/Real-ESRGAN/blob/master/docs/anime_video_model.md 
and
https://github.com/xinntao/Real-ESRGAN/blob/master/docs/anime_comparisons.md
