### ISSUE TITLE
修复一些10M以上的图片时，会突然闪退，然后没有修复成功

### ISSUE THREAD

**Issue by Minori-ty** [xinntao/Real-ESRGAN#288]
使用windows.exe修复一些10M以上的图片时，会突然闪退，然后没有修复成功。或者是修复成功了，但是预览图显示半张黑色。

**Comment by Minori-ty** [comment]
![image](https://user-images.githubusercontent.com/79521943/160880446-739af56d-2de3-4989-b424-dd48df2c499e.png)

**Comment by 1428900707** [comment]
我也出现了类似的问题，修复的是一张大小为14M的图片，每次修复进度到44%的时候就会闪退

**Comment by Minori-ty** [comment]
> 我也出现了类似的问题，修复的是一张大小为14M的图片，每次修复进度到44%的时候就会闪退

闪退倒不清楚，不过像这种半黑的，好像是文件显示的问题。把图片移到其他位置就能正常显示了。
