### ISSUE TITLE
numpy version requirement loop

### ISSUE THREAD

**Issue by AsuxAX** [xinntao/Real-ESRGAN#292]
Okay, so after downloading all the necessary modules, I'm always stuck in a loop.
It first said that gfpgan needed a numpy version of 1.21 or below, which I installed; however, it afterwards stated that opencv requires a higher version than that required by gfpgan, which is 1.21; opencv requires 1.21.2 or above.
How can I fix this?

I'm quite new to Python by the way.

**Comment by DestroyTargetNonBasicLand** [comment]
Try updating numpy by using: `pip3 install numpy --upgrade`
