### ISSUE TITLE
Results in MSU Video Super Resolution Benchmark

### ISSUE THREAD

**Issue by Kirillova-Anastasia** [xinntao/Real-ESRGAN#30]
Hello,
[MSU Video Group](https://videoprocessing.ai/) has recently launched Video Super Resolution Benchmark and evaluated this algorithm.

Real-ESRGAN takes 8th place by subjective score, 17th place by PSNR, and 10th by our metric ERQAv1.0. Real-ESRNet takes 18th place by subjective score, 9th place by PSNR, and 18th by our metric ERQAv1.0. ESRGAN takes 7th place by subjective score, 8th place by PSNR, and 3th by our metric ERQAv1.0.  You can see the results [here](https://videoprocessing.ai/benchmarks/video-super-resolution.html).

If you have any other VSR method you want to see in our benchmark, we kindly invite you to participate.
You can submit it for the benchmark, following [the submission steps](https://videoprocessing.ai/benchmarks/video-super-resolution.html#participate).

**Comment by xinntao** [comment]
Thanks @Kirillova-Anastasia 

Real-ESRGAN are for image restoration, may not be suitable for video restoration~ 

Thanks for reporting~~
