### ISSUE TITLE
V0.2.5.0 Seems don't support to use with cpu anymore.

### ISSUE THREAD

**Issue by k79e** [xinntao/Real-ESRGAN#306]
It seems it used a function that not support to run with cpu only.
https://github.com/pytorch/pytorch/issues/74625

```
Error "slow_conv2d_cpu" not implemented for 'Half'
        Tile 1/12
Traceback (most recent call last):
  File "inference_realesrgan.py", line 124, in <module>
    main()
  File "inference_realesrgan.py", line 105, in main
    output, _ = upsampler.enhance(img, outscale=args.outscale)
  File "D:\Program1\Python38\lib\site-packages\torch\autograd\grad_mode.py", lin
e 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\Real-ESRGAN-master\realesrgan\utils.py", line 188, in enhance
    self.tile_process()
  File "E:\Real-ESRGAN-master\realesrgan\utils.py", line 146, in tile_process
    output_start_x:output_end_x] = output_tile[:, :, output_start_y_tile:output_
end_y_tile,
UnboundLocalError: local variable 'output_tile' referenced before assignment
```

**Comment by xinntao** [comment]
please add `--fp32` option to your command

**Comment by k79e** [comment]
It works!!

**Comment by mudit514** [comment]
Yes, it worked.

**Comment by nmunisa** [comment]
> please add `--fp32` option to your command

how can I add this? please help me

learn.lr_find() --fp32 
learn.recorder.plot()

#output:
LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-31-c7a9c29f9dd1>](https://localhost:8080/#) in <module>()
----> 1 learn.lr_find()
      2 learn.recorder.plot()

10 frames
[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in _conv_forward(self, input, weight, bias)
    442                             _pair(0), self.dilation, self.groups)
    443         return F.conv2d(input, weight, bias, self.stride,
--> 444                         self.padding, self.dilation, self.groups)
    445 
    446     def forward(self, input: Tensor) -> Tensor:

RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

**Comment by WASasquatch** [comment]
How can this be implemented for something like MindsEye Beta?

**Comment by RifkyA911** [comment]
> [<img alt="@k79e" width="40" height="40" src="https://avatars.githubusercontent.com/u/6483602?s=80&amp;v=4">](/k79e)
> Author
> ###

it will push CPU only, how to work with GPU too?
