### ISSUE TITLE
How to use realesr-animevideov3 for X1, X2, X3?

### ISSUE THREAD

**Issue by HolyWu** [xinntao/Real-ESRGAN#322]
In https://github.com/xinntao/Real-ESRGAN/blob/master/docs/anime_video_model.md it says `This model can also be used for X1, X2, X3`. But simply changing the upscale argument of SRVGGNetCompact from 4 to 1, 2 or 3 will give errors. So what's the correct way to do it? Thanks.

**Comment by LuisB79** [comment]
did you managed to fix it?

**Comment by kodxana** [comment]
Are you using PyTorch or Vulkan version?

**Comment by Ndron** [comment]
Just use scale parameter -s
`python inference_realesrgan.py -n realesr-animevideov3 -i inputs -s 1`
