### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by egorpezdir** [xinntao/Real-ESRGAN#323]
It is using my CPU and is therefore slow. How to utilize my GPU?

**Comment by egorpezdir** [comment]
solved by running this command
 `pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

**Comment by lerrel129** [comment]
thank you very much. It helped ;)
