### ISSUE TITLE
请问在哪可以看到生成器的网络结构

### ISSUE THREAD

**Issue by EgbertMeow** [xinntao/Real-ESRGAN#328]
作者您好，我没有在代码中找到生成器的arch文件，basicsr的arch文件夹下也没有ESRGAN的arch文件
请问在哪里可以看到ESRGAN的arch文件

**Comment by sunjian2015** [comment]
> 作者您好，我没有在代码中找到生成器的arch文件，basicsr的arch文件夹下也没有ESRGAN的arch文件 请问在哪里可以看到ESRGAN的arch文件

请问在哪儿能看到呢？

**Comment by EgbertMeow** [comment]
> > 作者您好，我没有在代码中找到生成器的arch文件，basicsr的arch文件夹下也没有ESRGAN的arch文件 请问在哪里可以看到ESRGAN的arch文件
> 
> 请问在哪儿能看到呢？

在安装的Basic
