### ISSUE TITLE
关于输出的图片全为黑色的问题

### ISSUE THREAD

**Issue by rayeesoft** [xinntao/Real-ESRGAN#330]
**一、运行环境：**
操作系统：Windows 11 专业版 21H2
处理器：Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz   2.90 GHz
显卡信息：NVIDIA GeForce RTX 1660Ti
```
(gfpgan) > nvidia-smi
Sat May 14 16:53:18 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.59       Driver Version: 512.59       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| 34%   30C    P8    18W / 130W |    509MiB /  6144MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       576    C+G   ...n1h2txyewy\SearchHost.exe    N/A      |
|    0   N/A  N/A      1552    C+G   C:\Windows\System32\dwm.exe     N/A      |
|    0   N/A  N/A      3100    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      3376    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A      3896    C+G   ...8bbwe\WindowsTerminal.exe    N/A      |
|    0   N/A  N/A      4120    C+G   C:\Windows\System32\dwm.exe     N/A      |
|    0   N/A  N/A      5608    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      6516    C+G   ...dows\System32\LogonUI.exe    N/A      |
|    0   N/A  N/A      6636    C+G   ...ge\Application\msedge.exe    N/A      |
|    0   N/A  N/A      7324    C+G   ...2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A      8444    C+G   ...210.39\msedgewebview2.exe    N/A      |
|    0   N/A  N/A     10088    C+G   ...ows\System32\WUDFHost.exe    N/A      |
|    0   N/A  N/A     10160    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     10424    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A     12744    C+G   ...210.39\msedgewebview2.exe    N/A      |
+-----------------------------------------------------------------------------+
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:36:24_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```

**二、相关软件**
Anaconda               4.10.3  
Python                    3.8.13
pytorch                   1.11.0

**三、使用过程**
最开始是使用 [GFPGAN](https://github.com/TencentARC/GFPGAN) 项目，按教程安装好，用示例的命令（`python inference_gfpgan.py -i inputs/whole_imgs -o results -v 1.3 -s 2`）进行测试，脸部分割、优化正常，但是输出的 restored_imgs 只有脸部，背景全为黑色。

关闭`-bg_upsampler`(指定一个不存在的smapler)后，restored_imgs里的图片输出正常，脸部得到优化，但背景还是模糊的（符合预期，因为没有使用背景优化），确定为realesrgan运行不正常。

下载了[Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN)的绿色版，功能正常，不会出现图片为黑色的情况。

克隆此项目的代码，按教程安装，用示例的命令（`python inference_realesrgan.py -n RealESRGAN_x4plus -i inputs --face_enhance`）进行测试，输出的图片全为黑色。

为排除操作系统问题，在wsl2下安装Ubuntu 20.04.4 LTS，再次进行上面的测试，问题一样。

搜索了issues，没有发现相关的问题，希望能得到帮助。

非常感谢，这个几个项目太棒了！

**Comment by gioia010321** [comment]
我也是

**Comment by gioia010321** [comment]
请问一下，关闭 的具体操作是否可以说一下

**Comment by Xseqt** [comment]
I hope it can come to mobile

**Comment by rayeesoft** [comment]
> 请问一下，关闭 的具体操作是否可以说一下
指定一个不存在的 -bg_upsampler，如
`python inference_gfpgan.py -i inputs/whole_imgs -o results -v 1.3 -s 2 -bg_upsampler not_exists`

**Comment by gioia010321** [comment]
克隆此项目的代码，测试运行`python inference_realesrgan.py -n RealESRGAN_x4plus -i inputs --fp32`，跟改了这个后缀可以运行，原来`--face_enhance`只识别真人的脸，我觉得应该是后缀调用的关系，看着提示试试看应该就可以了

**Comment by gioia010321** [comment]
克隆此项目的代码，测试运行，更改了  python inference_realesrgan.py -n RealESRGAN_x4plus -i inputs --fp32  这个后缀可以运行，原来--face_enhance 只识别真人的脸，我觉得应该是后缀调用的关系，看着提示试试看应该就可以了

**Comment by rayeesoft** [comment]
@gioia010321 
非常感谢您的提醒，我测试了，RealESRGAN项目示例命令加上`--fp32`后，果然输出正常了！

在[GFPGAN](https://github.com/TencentARC/GFPGAN)项目中使用时，需要修改inference_gfpgan.py的76行，half=False，再用示例命令`python inference_gfpgan.py -i inputs/whole_imgs -o results -v 1.3 -s 2`，restored_imgs里的图片输出正常，脸部得到优化，背景也得到了优化。

但遇到一点疑惑，在修改inference_gfpgan.py的76行时，注释提示：`# need to set False in CPU mode`，难道我修改后之所以成功，是使用了CPU，没有使用CUDA? 我又进一步阅读了RealESRGAN项目的示例代码，Real-ESRGAN/realesrgan/utils.py第38行，是判断是否支持CUDA，以设置pytorch的设备，print(self.device)，运行后输出为：cuda，表示cuda正常的。我手动将device设置为‘cpu’，再次运行测试代码，明显感觉速度慢很多，证明cuda是生效了的。那么，RealESRGANer的half参数，究竟是什么作用呢？只是决定运算精度，还是决定cpu/cuda模式？

half设置为False后，目前一切正常。

再次感谢 @gioia010321 ，感谢作者！

**Comment by xinntao** [comment]
half 是使用 pytorch 的fp16精度，可以减少显存使用 ，加快推理速度。 

@rayeesoft 你这边是使用fp16 就会出现 图片全为黑色是吗？

**Comment by rayeesoft** [comment]
@xinntao 是的， half=True就会图片全为黑色，设置为False就正常。还需要我提供更详细的系统信息、硬件信息吗？

**Comment by Yeats-CJ** [comment]
> @gioia010321 非常感谢您的提醒，我测试了，RealESRGAN项目示例命令加上`--fp32`后，果然输出正常了！
> 
> 在[GFPGAN](https://github.com/TencentARC/GFPGAN)项目中使用时，需要修改inference_gfpgan.py的76行，half=False，再用示例命令`python inference_gfpgan.py -i inputs/whole_imgs -o results -v 1.3 -s 2`，restored_imgs里的图片输出正常，脸部得到优化，背景也得到了优化。
> 
> 但遇到一点疑惑，在修改inference_gfpgan.py的76行时，注释提示：`# need to set False in CPU mode`，难道我修改后之所以成功，是使用了CPU，没有使用CUDA? 我又进一步阅读了RealESRGAN项目的示例代码，Real-ESRGAN/realesrgan/utils.py第38行，是判断是否支持CUDA以设置pytorch的设备，print(self.device)，运行后输出为：cuda，表示自动选择使用了cuda。我手动将device设置为‘cpu’，再次运行测试代码，明显感觉速度慢很多，证明cuda是生效了的。那么，RealESRGANer的half参数，究竟是什么作用呢？只是决定运算精度，还是决定cpu/cuda模式？
> 
> half设置为False后，目前一切正常。
> 
> 再次感谢 @gioia010321 ，感谢作者！

只是决定了精度，之所以遇到这种情况可能是你的显卡或者安装的cuda不支持fp16导致的，我也遇到了这个问题

**Comment by wiwii** [comment]
真的和精度有关系。我用默认的fp16就全黑，fp32就有图。本地有其他用fp16的都经过cuda，所以是支持fp16。
