### ISSUE TITLE
Didn't use Cpu on m1 Mac

### ISSUE THREAD

**Issue by Percivalllll** [xinntao/Real-ESRGAN#34]
I've been using the program for a while, and it goes well. However, I found that it barely use CPU on m1, while the GPU is fully loaded, the Cpu is barely used.
Does it use Cpu on other platform or it only use gpu? I've heard that apple has built-in machine learning units in their m1 chip, maybe we can make use of them in a future update.

**Comment by xinntao** [comment]
Did you use the executable files or the PyTorch env?

Actually, I am not familiar with the deployment, I will search for it. It would be great if you could give more information.

**Comment by Percivalllll** [comment]
I used the executable file, the dependencies were somehow not installing.
It is already running on an acceptable speed, it seems that the machine learning feature is only available on macOS with their Metal api, and yours is written with Vulkan, here's the website
https://developer.apple.com/documentation/coreml

**Comment by xinntao** [comment]
@Percivalllll 
Thanks for your information. 

The improvement of using mac ml unit is out of my skill sets :stuck_out_tongue_closed_eyes:  
So, sorry that I cannot provide such features.

**Comment by RarogCmex** [comment]
@xinntao  @Percivalllll There are no public api for Apple Neural Engine (ANE). It is usable only with Apple ML Core framework:
https://github.com/hollance/neural-engine/blob/master/docs/programming-ane.md
Suggest to close issue.
