### ISSUE TITLE
自荐一下自己开发的GUI页面（Electron）

### ISSUE THREAD

**Issue by ArSrNa** [xinntao/Real-ESRGAN#341]
通过Websocket通信，用nodejs写的一个gui页面
目前可以批量处理
在这之后我还写了一个专门用腾讯云GPU服务器来跑的方案
程序已开源：
Coding：https://arsrna.coding.net/public/aresrgan/apps/git
Github：https://github.com/ArSrNa/ArESRGAN-GUI

下载：https://www.arsrna.cn/app/esrgan/
![image](https://user-images.githubusercontent.com/42886855/209089505-056435ef-2793-442c-bbf6-af50360e3161.png)

**Comment by ArSrNa** [comment]
附上：
腾讯云GPU服务器的方案：https://cloud.tencent.com/developer/article/2011313

**Comment by Glaukus** [comment]
要密码的啊，打不开

**Comment by ArSrNa** [comment]
> 

文件密码 w6ho

**Comment by ArSrNa** [comment]
视频版的GUI同时也做出来了 https://www.arsrna.cn/app/esrgan/
