### ISSUE TITLE
huggingface spaces port

### ISSUE THREAD

**Issue by AK391** [xinntao/Real-ESRGAN#36]
Hi I am looking to port this to huggingface spaces and getting this error

Collecting basicsr>=1.3.3.10
  Downloading basicsr-1.3.3.10.tar.gz (131 kB)
[91m    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-17oc2oxy/basicsr_ed5642abb2de4ee78654eca90f718aa2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-17oc2oxy/basicsr_ed5642abb2de4ee78654eca90f718aa2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-i7jyt39j
         cwd: /tmp/pip-install-17oc2oxy/basicsr_ed5642abb2de4ee78654eca90f718aa2/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-17oc2oxy/basicsr_ed5642abb2de4ee78654eca90f718aa2/setup.py", line 8, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'

here is the requirements.txt file

https://huggingface.co/spaces/akhaliq/Real-ESRGAN/blob/main/requirements.txt

**Comment by AK391** [comment]
@xinntao

**Comment by xinntao** [comment]
@AK391 
Hi, it seems that you have not installed pytorch. You may need to first install pytorch `pip install torch` or `pip install -r requirements.txt`

**Comment by AK391** [comment]
@xinntao Hi torch is installed, I did pip freeze afterwards and it is there
<img width="430" alt="Screen Shot 2021-08-16 at 4 51 54 PM" src="https://user-images.githubusercontent.com/81195143/129661733-286913f0-c631-4ff1-9537-8ca228109b09.png">

**Comment by AK391** [comment]
@xinntao also have basicsr==1.3.3.3 showing with pip freeze

**Comment by AK391** [comment]
resolved

**Comment by john990** [comment]
Hello, how did you solve it? I also encountered the same problem, thank you.
