### ISSUE TITLE
linux 版本的可执行文件，运行出错

### ISSUE THREAD

**Issue by helloxuejuxi** [xinntao/Real-ESRGAN#369]
段错误 (核心已转储),运行的命令是./realesrgan-ncnn-vulkan -i input.jpg -o output.png，弄的linux系统除了cd命令，其他命令都是段错误 (核心已转储)，怎么回事？谢谢

**Comment by helloxuejuxi** [comment]
这个错误好像和glibc有关系，glibc去掉就没这个错，可是报告./realesrgan-ncnn-vulkan: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./realesrgan-ncnn-vulkan)，哎，没辙了，折腾了好久

**Comment by helloxuejuxi** [comment]
这个问题暂时关闭，另一台电脑是ubuntu21.04，自带的glibc最高版本能到2.33，直接可运行，没任何错误，看样子如果自带的glibc版本低于2.29，还是得升级glibc，升级成功回来继续总结。

**Comment by wyf903990046** [comment]
./realesrgan-ncnn-vulkan: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./realesrgan-ncnn-vulkan)
./realesrgan-ncnn-vulkan: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./realesrgan-ncnn-vulkan)
这个还能有救吗，系统应该是centos7的，gcc最高支持4.8.5
