### ISSUE TITLE
Will the model use Neural Engine on Apple M1 chip

### ISSUE THREAD

**Issue by blacklein** [xinntao/Real-ESRGAN#378]
Will the model use Neural Engine on Apple M1 chip? If not, is there any plan to add that feature? Thank you!

**Comment by zcaceres** [comment]
Based on my attempts the answer seems to be no.

**Comment by kodxana** [comment]
<img width="455" alt="Screenshot 2022-07-06 at 00 20 26" src="https://user-images.githubusercontent.com/16674412/177426690-91df5995-b31e-463a-8e9f-649e476cb27e.png">
Works good on M1 :)

**Comment by kodxana** [comment]
<img width="301" alt="Screenshot 2022-07-06 at 00 27 52" src="https://user-images.githubusercontent.com/16674412/177427543-2646c1e6-c501-4e2e-b7ee-1e693ca251b7.png">
At least Vulcan version is utilising GPU :)

**Comment by blacklein** [comment]
what is the app of GPU History screenshot?

**Comment by blacklein** [comment]
ok, thank you

**Comment by zcaceres** [comment]
> <img alt="Screenshot 2022-07-06 at 00 27 52" width="301" src="https://user-images.githubusercontent.com/16674412/177427543-2646c1e6-c501-4e2e-b7ee-1e693ca251b7.png">
> 
> At least Vulcan version is utilising GPU :)

I couldn't get that to work. Can you share what version/commands that you ran? @kodxana 

Thank you!

**Comment by Langhalsdino** [comment]
I setup my environment according to the guide [INSTALL_MAC.md](https://github.com/lstein/stable-diffusion/blob/main/docs/installation/INSTALL_MAC.md) and defined in [environment-mac.yaml](https://github.com/lstein/stable-diffusion/blob/main/environment-mac.yaml).

Furthermore i used the follwoing ('mps') enables the upscaling device:
```
upsampler = RealESRGANer(
            model_path=model_path,
            ....
            half=False,
            device='mps'
        )
```

**Comment by cukabeka** [comment]
Unfortunately, the INSTALL_MAC link is down now. Is there a current solution for M1 to run ESRGAN?

**Comment by pims** [comment]
@cukabeka 

```diff
diff --git a/inference_realesrgan.py b/inference_realesrgan.py
index 0a8cc43..365715f 100644
--- a/inference_realesrgan.py
+++ b/inference_realesrgan.py
@@ -51,6 +51,8 @@ def main():
         help='Image extension. Options: auto | jpg | png, auto means using the same extension as inputs')
     parser.add_argument(
         '-g', '--gpu-id', type=int, default=None, help='gpu device to use (default=None) can be 0,1,2 for multi-gpu')
+    parser.add_argument(
+        '--device', type=str, default=None, help='gpu device to use')

     args = parser.parse_args()

@@ -113,7 +115,8 @@ def main():
         tile_pad=args.tile_pad,
         pre_pad=args.pre_pad,
         half=not args.fp32,
-        gpu_id=args.gpu_id)
+        gpu_id=args.gpu_id,
+        device=args.device)

     if args.face_enhance:  # Use GFPGAN for face enhancement
         from gfpgan import GFPGANer
```

and then use the inference script as:
```
python inference_realesrgan.py -n RealESRGAN_x4plus -i inputs --fp32 --device mps
```
