### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [xinntao/Real-ESRGAN#380]
I'm trying to train a model with just one GPU, but after a lot of trouble getting everything set up, it reaches the point it builds the module but then a warning appears that PyTorch will create 5 working processes, then it breaks at lines 11, 120 and 48 of train.py, with the root cause being this:
`total_epochs = math.ceil(total_iters / (num_iter_per_epoch))`
`ZeroDivisionError: division by zero`

-----------------------------------------------------
EDIT: the log after the text in the train_finetune txt is:
```2022-07-02 16:42:20,191 INFO: Dataset [RealESRGANPairedDataset] - Menudo is built.
C:\Users\<me>\anaconda3\lib\site-packages\torch\utils\data\dataloader.py:557: UserWarning: This DataLoader will create 5 worker processes in total. Our suggested max number of worker in current system is 4 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "D:\realesrgan-ncnn-vulkan-20220424-windows\train\realesrgan\train.py", line 11, in <module>
    train_pipeline(root_path)
  File "C:\Users\<me>\anaconda3\lib\site-packages\basicsr\train.py", line 120, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "C:\Users\<me>\anaconda3\lib\site-packages\basicsr\train.py", line 48, in create_train_val_dataloader
    total_epochs = math.ceil(total_iters / (num_iter_per_epoch))
ZeroDivisionError: division by zero

**Comment by l-l-l-l-l-l** [comment]
Changing the comand from one GPU to multiple GPUs (but number changed to 1) gives me a chain of errors that point to CUDA.

Is this software only compatible with Nvidia or can you change your GPU to the correct one (or even to CPU, if needed)?

**Comment by l-l-l-l-l-l** [comment]
Found the error. It was just thatmeta_info_DIV2K_sub_pair.txt had been incorrectly created

**Comment by haniye7122** [comment]
> Found the error. It was just thatmeta_info_DIV2K_sub_pair.txt had been incorrectly created

how did you fixed the problem?
