### ISSUE TITLE
train on one gpu, windows machine

### ISSUE THREAD

**Issue by mohammadmardani** [xinntao/Real-ESRGAN#39]
I am trying to train on one gpu windows machine:
# general settings
name: train_RealESRNetx4plus_1000k_B12G4_fromESRGAN
model_type: RealESRNetModel
scale: 4
num_gpu: 1 #4
manual_seed: 0

but when I run:
python -m torch.distributed.launch --nproc_per_node=4 --master_port=4321 realesrgan/train.py -opt options/train_realesrnet_x4plus.yml --launcher pytorch --auto_resume

I get the following error:
 line 625, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "    raise RuntimeError("Distributed package doesn't have NCCL "
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeErrorraise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError:
RuntimeError: Distributed package doesn't have NCCL built inRuntimeError: Distributed package doesn't have NCCL built in
: Distributed package doesn't have NCCL built in
Distributed package doesn't have NCCL built in
.
.
...
line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
*****************************************
  D:\SR_v01\Real-ESRGAN\train.py FAILED
=========================================
Root Cause:
[0]:
  time: 2021-08-18_10:28:49
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 13540)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=========================================
Other Failures:
[1]:
  time: 2021-08-18_10:28:49
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 13676)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2021-08-18_10:28:49
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 14228)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[3]:
  time: 2021-08-18_10:28:49
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 13656)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
*****************************************

I tried it in WSL too. same error raised.
could you give us a guide?

**Comment by xinntao** [comment]
For one gpu, there is no need to use distributed training, try

`python realesrgan/train.py -opt options/train_realesrnet_x4plus.yml` directly:-)

**Comment by mohammadmardani** [comment]
I tried that too.
it will raise:
raise KeyError(key) from None
KeyError: 'RANK

if I set the os.environ['RANK'] = '0'
then other keyerror's will raise

**Comment by xinntao** [comment]
Could you please paste more detailed info?  from which line raise this error?

**Comment by mohammadmardani** [comment]
before setting the RANK to 0:
![image](https://user-images.githubusercontent.com/52232648/129828932-065a9710-926c-4f64-ab44-c4b0f14c3a7b.png)

after setting it to 0:

![image](https://user-images.githubusercontent.com/52232648/129829023-766c5a33-a0e1-4daa-87c2-3f3898904073.png)

**Comment by xinntao** [comment]
Please use `python realesrgan/train.py -opt options/train_realesrnet_x4plus.yml`

do not add --laucher pytorch

**Comment by mohammadmardani** [comment]
sorry was busy for few days.
now I have this problem:
![image](https://user-images.githubusercontent.com/52232648/131470616-18b526ee-2fa0-4937-960c-607e787296bb.png)
