### ISSUE TITLE
ffmpeg将视频转图片有什么硬件加速的指令吗？

### ISSUE THREAD

**Issue by Minori-ty** [xinntao/Real-ESRGAN#405]
用ffmpeg将视频转图片再转视频，要花好长的时间，自己的GPU都没用到，想问一下有什么硬件加速的指令吗？

**Comment by Minori-ty** [comment]
用ffmpeg将视频转图片再转视频，要花好长的时间，自己的GPU都没用到，想问一下有什么硬件加速的吗？

**Comment by czha8903** [comment]
Hi, u can try to use "-hwaccel nvdec".
Some version of ffmpeg support GPU
