### ISSUE TITLE
 local variable 'model' 

### ISSUE THREAD

**Issue by Innerbattles** [xinntao/Real-ESRGAN#410]
Hello guys i hope can u guys can assist me i have this problem 

  File "C:\Users\fragb\Desktop\Real-ESRGAN-master\inference_realesrgan.py", line 128, in <module>
    main()
  File "C:\Users\fragb\Desktop\Real-ESRGAN-master\inference_realesrgan.py", line 74, in main
    model=model,
UnboundLocalError: local variable 'model' referenced before assignment

Before i add 

netscale = 4

in the line 46 to solve 
UnboundLocalError: local variable 'netscale' referenced before assignment

![imagen_2022-08-16_221808769](https://user-images.githubusercontent.com/39067662/185040468-2b3044da-b11a-4408-9453-9b7dfc7fd6ba.png)

**Comment by lallish** [comment]
I get similar error when trying to run the inference_realesrgan.py, but my error is:
`UnboundLocalError: local variable 'output_tile' referenced before assignment`

**Comment by aqsaa2** [comment]
![error](https://github.com/xinntao/Real-ESRGAN/assets/132770829/d60162da-3caa-452d-94d8-c6ac7f68f163)
can anyone help me with this error plz?
