### ISSUE TITLE
ESRGAN massive CPU bottleneck

### ISSUE THREAD

**Issue by TechnoMasterBoy** [xinntao/Real-ESRGAN#419]
Like I mentioned in this discussion: https://github.com/xinntao/Real-ESRGAN/discussions/269
ESRGAN is severely bottlenecked by my beastly CPU even though my GPU is trash.
Ryzen 9 5900x:
![unknown](https://user-images.githubusercontent.com/90092517/185788324-a882f25f-87a7-497a-b310-8cb2e1954efa.png)
GTX 1080:
![unknown](https://user-images.githubusercontent.com/90092517/185788329-a7330b84-7d91-4ee3-9539-948473782d23.png)
My GPU is load is currently at 19% average while CPU is around 90-95%.
It's literally telling me it's IDLING:
![unknown](https://user-images.githubusercontent.com/90092517/185788394-72b2ac36-3baa-446c-964f-4744ee73eefd.png)
This is using the portable NCNN version with realesr-animevideov3 model at 4x, going from 628x480 to 2512x1920.

**Comment by kiam001** [comment]
hmm no issues with a rtx 2060

**Comment by kiam001** [comment]
![image](https://user-images.githubusercontent.com/10757700/187500839-96904c1d-5fa3-401b-980b-a9c95f1b8094.png)

**Comment by TechnoMasterBoy** [comment]
> hmm no issues with a rtx 2060

Might be because RTX 2060 is supposedly weaker than GTX 1080 though, which might explain why your GPU has high usage.
But I also have no idea what model you used and at what scale. I assume 4x scale since you posted that in the other issue. But without knowing the resolution, that means very little.

**Comment by lextra2** [comment]
GPU: AMD Radeon RX 5700
CPU: AMD Ryzen 3900X
OS: Windows 10

Works for me.

I get about 8% CPU usage and ~95% GPU (Compute 0) usage with `realesrgan-ncnn-vulkan.exe v0.2.5.0` `realesr-animevideov3-x2` 1280x720 > 2560x1440 with PNG as input & output.

**Comment by TechnoMasterBoy** [comment]
> GPU: AMD Radeon RX 5700 CPU: AMD Ryzen 3900X OS: Windows 10
> 
> Works for me.
> 
> I get about 8% CPU usage and ~95% GPU (Compute 0) usage with `realesrgan-ncnn-vulkan.exe v0.2.5.0` `realesr-animevideov3-x2` 1280x720 > 2560x1440 with PNG as input & output.

Wow okay, I found the issue.
The batch command I use is this:
for %%a in ("*.png") do C:\ESRGAN\realesrgan-ncnn-vulkan.exe -i "%%a" -o "Output\%%~na.png" -n realesr-animevideov3 -s 2
And for some reason, that makes it take insanely long compared to just telling it to input one folder and output to another.
Telling it to use a folder instead of that command makes my GPU run at full load according to GPU-Z. Even if taskmanager shows only like 20% 3D. Compute 0 has always shown me 0%
Thanks guys for in a way making me experiment a bit to find out the issue.

**Comment by lextra2** [comment]
> > GPU: AMD Radeon RX 5700 CPU: AMD Ryzen 3900X OS: Windows 10
> > Works for me.
> > I get about 8% CPU usage and ~95% GPU (Compute 0) usage with `realesrgan-ncnn-vulkan.exe v0.2.5.0` `realesr-animevideov3-x2` 1280x720 > 2560x1440 with PNG as input & output.
> 
> Wow okay, I found the issue. The batch command I use is this: for %%a in ("*.png") do C:\ESRGAN\realesrgan-ncnn-vulkan.exe -i "%%a" -o "Output%%~na.png" -n realesr-animevideov3 -s 2 And for some reason, that makes it take insanely long compared to just telling it to input one folder and output to another. Telling it to use a folder instead of that command makes my GPU run at full load according to GPU-Z. Even if taskmanager shows only like 20% 3D. Compute 0 has always shown me 0% Thanks guys for in a way making me experiment a bit to find out the issue.

I'm glad you fixed it. For future references, here are my exact steps:

1. Create 2 folders named input & output 

![image](https://user-images.githubusercontent.com/20690384/187598024-27f5a918-7cb6-4f59-8726-d58d37838ec7.png)

3. Use this command to create input frames: `ffmpeg -i input.mkv input/frame%08d.png`
4. Use this command to start esrgan: `realesrgan-ncnn-vulkan -i input -o output -s 2`
5. Use this command to make a video: `ffmpeg -i output/frame%08d.png -c:v libx264 -crf 10 -r 24000/1001 -pix_fmt yuv420p output.mkv`
