### ISSUE TITLE
How to run the latest model realesr-general-x4v3?

### ISSUE THREAD

**Issue by jnie028** [xinntao/Real-ESRGAN#427]
Is there any code to support this model? 

Thanks in advance!

-JN

**Comment by VaslD** [comment]
You should be able to use the new model by calling with `-m` + new model name after dropping `.pth` in `models`.

e.g. `./realesrgan-ncnn-vulkan -m realesr-general-x4v3 -i ...`

**Comment by EricLarge** [comment]
It seems that the software is looking for a .param file along with the .pth file, and that doesn't seem to have been provided.  Is this something we need to generate and if so how?

**Comment by arisioz** [comment]
> You should be able to use the new model by calling with `-m` + new model name after dropping `.pth` in `models`.
> 
> e.g. `./realesrgan-ncnn-vulkan -m realesr-general-x4v3 -i ...`

Judging from `inference_realesrgan.py` you cannot use an arbitrary model, the accepted models are: 
RealESRGAN_x4plus 
RealESRNet_x4plus 
RealESRGAN_x4plus_anime_6B 
RealESRGAN_x2plus
realesr-animevideov3

Which made me wonder on how they managed to make `realesr-general-x4v3.pth` only 4.66MB where the original `RealESRGAN_x4plus.pth` was almost 64MB.

Code for choosing the model which limits which input to model:

`    args.model_name = args.model_name.split('.')[0]
    if args.model_name in ['RealESRGAN_x4plus', 'RealESRNet_x4plus']:  # x4 RRDBNet model
        model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=23, num_grow_ch=32, scale=4)
        netscale = 4
    elif args.model_name in ['RealESRGAN_x4plus_anime_6B']:  # x4 RRDBNet model with 6 blocks
        model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=6, num_grow_ch=32, scale=4)
        netscale = 4
    elif args.model_name in ['RealESRGAN_x2plus']:  # x2 RRDBNet model
        model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=23, num_grow_ch=32, scale=2)
        netscale = 2
    elif args.model_name in ['realesr-animevideov3']:  # x4 VGG-style model (XS size)
        model = SRVGGNetCompact(num_in_ch=3, num_out_ch=3, num_feat=64, num_conv=16, upscale=4, act_type='prelu')
        netscale = 4`

**Comment by jnie028** [comment]
Thanks for author's code updating yesterday. We can run the new model from now on.
Case closed.
