### ISSUE TITLE
segmentation fault when running from a different folder on Mac

### ISSUE THREAD

**Issue by sergey-kritskiy** [xinntao/Real-ESRGAN#440]
I'm using the portable version on a Mac. If I open Terminal on the realesrgan folder and run
`./realesrgan-ncnn-vulkan -i /path/to/input.jpg -o /path/to/output.jpg`
it works. 
However if I run it from any other folder, for example
```
cd ..
./realesrgan-ncnn-vulkan-20220424-macos/realesrgan-ncnn-vulkan -i /path/to/input.jpg -o /path/to/output.jpg

```
I'm getting a segmentation error:
`zsh: segmentation fault  ./realesrgan-ncnn-vulkan-20220424-macos/realesrgan-ncnn-vulkan -i /path/to/input.jpg -`
Running from a different folder on Windows works fine. I was wondering if there's a way to avoid this on my side or fix on your side? Thank you.

**Comment by Emanuelcarvalho2004** [comment]
Look the settings

**Comment by sergey-kritskiy** [comment]
> Look the settings

I don't know what you mean by that. Settings of what?

**Comment by xinntao** [comment]
I do not have the mac environment. To wait for someone else to fix it 😃

**Comment by hay** [comment]
@sergey-kritskiy seems you need to specify the complete path of the models using the `-m` flag when using the command on files outside of its root folder.

**Comment by sergey-kritskiy** [comment]
@hay oh wow, thank you for the tip, it worked! I also had to provide full paths to input and output images

**Comment by rkhyper** [comment]
python3 inference_realesrgan.py -n RealESRGAN_x4plus -i input.png -o output.png -s 2 --fp32 

i have same problem

**Comment by david1asher** [comment]
> @hay oh wow, thank you for the tip, it worked! I also had to provide full paths to input and output images

care to give an example for a run command that worked?

**Comment by david1asher** [comment]
i have same error when i run it with any of these flags: `-n` `-m`
