### ISSUE TITLE
Why not use pixel shuffle instead of interpolate('mode='nearest'') for upsampling?

### ISSUE THREAD

**Issue by Ken1256** [xinntao/Real-ESRGAN#46]
Any special reason?

**Comment by LitleCarl** [comment]
Same question confusing me. Hope for answer with quantitive benchmark.

**Comment by xinntao** [comment]
For upsampling, using nearest interpolation and pixel shuffle is both OK.

As interpolation with the nearest mode is simpler, we use this upsampling in ESRGAN (also in Real-ESRGAN).
They perform similarly in visual quality. As for the quantitative results, pixel shuffle may be better as it has more parameters.
