### ISSUE TITLE
A problem about the inference of gray image(8 bit image)

### ISSUE THREAD

**Issue by DsLipku** [xinntao/Real-ESRGAN#483]
When I try to restore 00017_gray.png this image(a gray, 8-bit image) ,

using command "python inference_realesrgan.py -n RealESRGAN_x4plus -i inputs --face_enhance --fp32",

the following problem occured:

Traceback (most recent call last):
  File "C:/Users/qingfeng/Desktop/Real-ESRGAN/inference_realesrgan.py", line 145, in main
    _, _, output = face_enhancer.enhance(img, has_aligned=False, only_center_face=False, paste_back=True)
  File "D:\Anaconda3\envs\Real-ESRGAN\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\Real-ESRGAN\lib\site-packages\gfpgan\utils.py", line 145, in enhance
    restored_img = self.face_helper.paste_faces_to_input_image(upsample_img=bg_img)
  File "D:\Anaconda3\envs\Real-ESRGAN\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 355, in paste_faces_to_input_image
    upsample_img = inv_soft_mask * pasted_face + (1 - inv_soft_mask) * upsample_img
**ValueError: operands could not be broadcast together with shapes (1404,2000,1) (1404,2000)** 

In this statement "upsample_img = inv_soft_mask * pasted_face + (1 - inv_soft_mask) * upsample_img",
the shape of inv_soft_mask is (1404,2000,1),  the shape of pasted_face is  (1404,2000,3)
and the shape of upsample_img is (1404,2000).

**Comment by DsLipku** [comment]
> 我也遇到这个问题了，你有好的解决办法吗

预处理一下灰度图，将灰度图的单通道复制成三通道，代码如下
![image](https://user-images.githubusercontent.com/62512366/203538196-e86a5c93-3b31-4382-a2f9-a81d16610c66.png)

**Comment by Dalaoyel** [comment]
> > 我也遇到这个问题了，你有好的解决办法吗
> 
> 预处理一下灰度图，将灰度图的单通道复制成三通道，代码如下 ![image](https://user-images.githubusercontent.com/62512366/203538196-e86a5c93-3b31-4382-a2f9-a81d16610c66.png)

这非常管用，谢谢你

**Comment by jackecust** [comment]
> > 我也遇到这个问题了，你有好的解决办法吗
> 
> 预处理一下灰度图，将灰度图的单通道复制成三通道，代码如下 ![image](https://user-images.githubusercontent.com/62512366/203538196-e86a5c93-3b31-4382-a2f9-a81d16610c66.png)

it is very good, really thanks
