### ISSUE TITLE
Question, how did you guys build the WIndows binary from python

### ISSUE THREAD

**Issue by devm21** [xinntao/Real-ESRGAN#5]
I have also been trying to ship one windows binary that would include all dependencies so people don't have to deal with windows install issues. Any tips on how you guys build the binaries for different environment? Much appreciated.

**Comment by xinntao** [comment]
@devm21 
This window binary file is generated with ncnn: https://github.com/Tencent/ncnn

You can more examples in [nihui](https://github.com/nihui)'s projects. 


Another way is to use pyinstaller, but it may not suitable for cnn network conversion.

**Comment by devm21** [comment]
@xinntao thanks for the tips. Yeah, I was trying the pyinstaller route, but found it rather difficult with large python projects.

**Comment by xinntao** [comment]
Right. 

I only used pyinstaller in this project: https://github.com/xinntao/HandyView, which is a small project with PyQt5. The problem is that the executable file is too large……

If you find another way that can convert python projects easily, please let me know. 
Thanks~

**Comment by devm21** [comment]
@xinntao yeah it's been a week kind of struggle, with different tools stuck on different errors, so ncnn might be the only thing that actually works this year. Do you mind to include your build script/instruction for the binary in the future?

**Comment by xinntao** [comment]
It is almost the same as https://github.com/nihui/realsr-ncnn-vulkan

You can refer to that project.

**Comment by samheather** [comment]
What tool did you use to generate the Mac portable binary?
