### ISSUE TITLE
REQUEST: 2x version of RealESRGAN_x4plus_anime_6B

### ISSUE THREAD

**Issue by dan64** [xinntao/Real-ESRGAN#523]
I would be nice if you could provide a 2x version of the model RealESRGAN_x4plus_anime_6B. My understanding is that there are artifacts in using  RealESRGAN_x4plus_anime_6B as 2x model, so it could be useful provide a specific 2x version of this model, since in my opinion is currently the best model for up-scaling anime movies.

**Comment by TechnoMasterBoy** [comment]
Use the AnimeVideo-v3 model instead for videos. It's the best for anime and you can use it with 2x, even 1x if you edit a few lines in notepad++.

**Comment by dan64** [comment]
Ok I will use AnimeVideo-v3, but in some case RealESRGAN_x4plus_anime_6B is still better. I like the thinning provided by RealESRGAN_x4plus_anime_6B, I can add aWarpSharp2 to AnimeVideo-v3 to get a similar thinning but RealESRGAN_x4plus_anime_6B introduces less artifacts.

**Comment by TechnoMasterBoy** [comment]
Here you go, I've altered the x4plus anime model to support 2x.
This assumes you use the ncnn portable version.
To use it, you just do -s 2 -n realesrgan-x2plus
Unfortunately, since it's just a simple edit, it takes just as long as upscaling with 4x, but it gets the job done without you having to worry about downscaling afterwards.
https://gofile.io/d/Nuo9UK

**Comment by dan64** [comment]
Thanks for your understanding.

**Comment by Comitant** [comment]
> Here you go, I've altered the x4plus anime model to support 2x. This assumes you use the ncnn portable version. To use it, you just do -s 2 -n realesrgan-x2plus Unfortunately, since it's just a simple edit, it takes just as long as upscaling with 4x, but it gets the job done without you having to worry about downscaling afterwards. https://gofile.io/d/Nuo9UK

Could you reupload this? I would also like to try it.

**Comment by FluffyDiscord** [comment]
Can we please get proper x2 version that will take less time to upscale than the x4 version?

**Comment by TechnoMasterBoy** [comment]
> > Here you go, I've altered the x4plus anime model to support 2x. This assumes you use the ncnn portable version. To use it, you just do -s 2 -n realesrgan-x2plus Unfortunately, since it's just a simple edit, it takes just as long as upscaling with 4x, but it gets the job done without you having to worry about downscaling afterwards. https://gofile.io/d/Nuo9UK
> 
> Could you reupload this? I would also like to try it.

Sorry I took so long. This link should be more permanent.
https://files.catbox.moe/kzabwo.7z


> Can we please get proper x2 version that will take less time to upscale than the x4 version?

I'd suggest using the animevideov3 instead if you want speed. Sometimes it even does a better job.
If you want a proper 2x version, you'll probably have to find a way to convert the .pth model as I doubt Xinntao will convert it himself.
Or just get a good GPU, upscaling 4 images from 1080p to 8k took as little as 17 seconds on a 3090 with the x4plus model.
Though the animevideov3 does it in 3 seconds.
If you want to request a proper x2 version, you should probably make a new issue, as this one is closed and becoming quite old.
