### ISSUE TITLE
Output file when running -s argument shows corruption of data

### ISSUE THREAD

**Issue by AlphaHasher** [xinntao/Real-ESRGAN#536]
I am running: [Real-ESRGAN ncnn Vulkan](https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan) and the `-s` argument only works for the default `realesr-animevideov3` model and not for anything other that is provided

all other models are stuck at 4x scale

Steps to recreate:
>realesrgan-ncnn-vulkan.exe -i input.jpg -o output.png -n realesrgan-x4plus -s 2

or
>realesrgan-ncnn-vulkan.exe -i input.jpg -o output.png -n realesrgan-x4plus-anime -s 2

Output (for both):
![output](https://user-images.githubusercontent.com/33443001/210119044-06da979f-fbaf-479f-a4a6-c989caf4fc8f.png)

**Comment by xeleoss** [comment]
Same problem
