### ISSUE TITLE
result looks strange on text area

### ISSUE THREAD

**Issue by tachikoma777** [xinntao/Real-ESRGAN#56]
result looks strange on text area (like creating a new font), I know its hard to restoration, did you know any project which uses reference image (such as the middle image) to get good result?
![image](https://user-images.githubusercontent.com/6949661/131095866-6af6e876-bdb9-492a-81b6-034ea1532ae6.png)

**Comment by xinntao** [comment]
C2-Matching is a reference-based SR framework. 
You can perform C2-matching (with super-resolution) and then down-sample it to the desired size. Or you can retrain your own model without SR>

**Comment by lyp19921126** [comment]
> @tachikoma777
> 
> I will improve the Real-ESRGAN by fine-tuning on images with text. The preliminary results (on English text) are promising, and I will extent it.
> 
> For reference-based SR, you may check: https://github.com/yumingj/C2-Matching

Hello, I would like to ask, this EDRGAN and C2-Matching , two papers are respectively designed for what kind of super-resolution task, whether the image with text more fit for C2-Matching?
