### ISSUE TITLE
x4plus vs x4plus_netD

### ISSUE THREAD

**Issue by C00reNUT** [xinntao/Real-ESRGAN#59]
Hello,

thank you for this amazing tool. 

May I ask you what is the difference between RealESRGAN_x4plus and RealESRGAN_x4plus_netD?

**Comment by xinntao** [comment]
RealESRGAN_x4plus_netD is the discriminator, while RealESRGAN_x4plus is the generator/restorer.

RealESRGAN_x4plus_netD cannot be used for restoration but for someone that wants to fine-tune RealESRGAN_x4plus with their own data

**Comment by C00reNUT** [comment]
Thank you!
