### ISSUE TITLE
Over-use/High performance of CPU, RAM and Disk

### ISSUE THREAD

**Issue by Ryosama2** [xinntao/Real-ESRGAN#597]
![image](https://user-images.githubusercontent.com/115549537/229029094-10034439-278e-47d7-955e-c7548d9e3883.png)

This is my laptop status when it runs the Real-ESRGAN execution.
My laptop configuration:
![image](https://user-images.githubusercontent.com/115549537/229029282-79bd1d6e-171a-45ca-afe9-70bb33c38ece.png)

Any idea to solve this issue? :((

**Comment by ThatPlasma** [comment]
did you ever solve this?
