### ISSUE TITLE
Image blocks caused by upscale ratio.

### ISSUE THREAD

**Issue by 2727995853** [xinntao/Real-ESRGAN#605]
With the default setting, everything is fine, however, after I changed the upscale ratio, which is not 4, the default, processed images seem to be separated into blocks. (First is the raw image, second is the processed image with ratio of 2)
![123](https://user-images.githubusercontent.com/108162087/231208849-ee04ac9c-eaae-4ec8-b59e-44016d5307a0.png)
![123_scale-2](https://user-images.githubusercontent.com/108162087/231208920-9f8f1429-037e-42bd-9ed4-b025e1af9f55.png)

**Comment by luozi3** [comment]
hi,I have the same problem, can you tell me your solution?

**Comment by luozi3** [comment]
https://github.com/xinntao/Real-ESRGAN/issues/554
Click here to find a solution
