### ISSUE TITLE
Idea for video and image optimization

### ISSUE THREAD

**Issue by myname1111** [xinntao/Real-ESRGAN#61]
Lets start with images. basically if we have two section that are more or less similar, it would be a waste to enhance this section when a similar section has been enhanced, so we could instead edit a similar section. for videos it's more or less the same but with time instead of x and y.

**Comment by xinntao** [comment]
Thanks for your suggestion:-) It is an intuition to decrease the processing time for video. 
We are also developing video algorithms 😄

**Comment by medram** [comment]
That's really great :D

**Comment by 78Alpha** [comment]
I believe https://github.com/AaronFeng753/Waifu2x-Extension-GUI
Has implemented something like that for everything they support, REAL-ESRGAN included

**Comment by brunoais** [comment]
> I believe https://github.com/AaronFeng753/Waifu2x-Extension-GUI Has implemented something like that for everything they support, REAL-ESRGAN included

However, they don't support linux. I can't run it properly
