### ISSUE TITLE
出图颈部不正常

### ISSUE THREAD

**Issue by hktalent** [xinntao/Real-ESRGAN#610]
Mac OS, intel cpu i7
```
python inference_realesrgan.py -n RealESRGAN_x4plus -i $HOME/MyWork/51pwn4ai/data/img_47.jpg --face_enhance --fp32
```
<img width="667" alt="image" src="https://user-images.githubusercontent.com/18223385/232033847-d267be97-ec0f-44f3-bf28-f2fbb12d3ab1.png">

**Comment by ANYMS-A** [comment]
老哥我也遇到类似的问题 怎么解决的？

**Comment by hktalent** [comment]
我放弃了 @ANYMS-A
