### ISSUE TITLE
How to get the dataset for fune tuning using anime model?

### ISSUE THREAD

**Issue by splinter21** [xinntao/Real-ESRGAN#64]
Are the degradation methods the same as real world?
And how to get the HR anime dataset (what anime dataset did you use?)?
Should I add some gaussian noise and jpeg compress artifact(the same as waifu2x) for training anime model?

**Comment by xinntao** [comment]
Hi @splinter21 
1. the degradation model is the same as that for general images. 
2. We construct a high-quality anime dataset. You can construct your own. 
3. the current degradation model has already considered the Gaussian noise and jpeg compression artifacts.

**Comment by Ken1256** [comment]
@xinntao
Does anime need to perceive loss?
Is the D network the same as a general images?
Are everything the same except num_block=6?

**Comment by xinntao** [comment]
@Ken1256 
1. the anime model also has the perceptual loss
2. All the other settings keep the same, except the data and block numbers

**Comment by Kongsea** [comment]
> @Ken1256
> 
> 1. the anime model also has the perceptual loss
> 2. All the other settings keep the same, except the data and block numbers

The `block numbers` you mentioned is to mean the `network_g` or `network_d`?
Do you try to change the ration of the three loss when adapting the anime model?
Could you please share the technical report of finetuning the anime model? Where can I find it? Thank you.
