### ISSUE TITLE
8x or 9x enhancing

### ISSUE THREAD

**Issue by Afshinshafei** [xinntao/Real-ESRGAN#655]
Hello guys! 
I have quick question which is, is it possible to finetune or train model with more than 4x enhancing for example 8x or 9x?
thank you in advance for your time.

**Comment by Jerchongkong** [comment]
Yes, it is possible to train a model at x8, x9, etc. resolutions. The only issue is that there are no pre-trained models available at those resolutions, so you will have to do it without one, meaning starting from scratch.
