### ISSUE TITLE
what's difference between RealESRGAN_x2plus and RealESRGAN_x4plus

### ISSUE THREAD

**Issue by XavierPixel** [xinntao/Real-ESRGAN#675]
Hi all
Does anyone know
what's difference between RealESRGAN_x2plus and RealESRGAN_x4plus？
2x scale and 4x scale？

**Comment by XavierPixel** [comment]
I use RealESRGAN_x2plus the output is still 4x scale up

**Comment by StarfuryT** [comment]
you need to make sure to set the upscaling parameter to either 2 or 4 when you call the function if you are using command line

the parameter is '-s', default being 4. The weight files are identical so the model itself can't tell what you want to do w/o you specifying it. If you want to use the x2 weights then set '-s 2'

**Comment by yrkgokfrrna4395** [comment]
@XavierPixel Hi!
Can you give me a try with your model(RealESRGAN_x2plus)? thanks!
karsion@126.com

**Comment by XavierPixel** [comment]
@ yrkgokfrrna4395  from Xiaoto's replys
"you need to make sure to set the upscaling parameter to either 2 or 4 when you call the function if you are using command line
the parameter is '-s', default being 4. The weight files are identical so the model itself can't tell what you want to do w/o you specifying it. If you want to use the x2 weights then set '-s 2' "

command:
python3 inference_realesrgan.py -i ./inputs/test  -o ./inputs/test_ai  -n RealESRGAN_x2plus  --fp32 -t 64 -s 2
the model will down automatically in inference_realesrgan.py, you can try.


Thanks & Best Regards
Xuming
Tel: 021-60586406
Mobile: 13585997096



发件人: yrkgokfrrna4395 ***@***.***>
日期: 星期四, 2023年8月24日 23:44
收件人: xinntao/Real-ESRGAN ***@***.***>
抄送: Xuming Fan ***@***.***>, Mention ***@***.***>
主题: Re: [xinntao/Real-ESRGAN] what's difference between RealESRGAN_x2plus and RealESRGAN_x4plus (Issue #675)

@XavierPixel<https://github.com/XavierPixel> Hi!
Can you give me a try with your model(RealESRGAN_x2plus)? thanks!
***@***.******@***.***>

―
