### ISSUE TITLE
 total_epochs = math.ceil(total_iters / (num_iter_per_epoch)),  ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by XavierPixel** [xinntao/Real-ESRGAN#703]
Hi all,
I try to run 
python realesrgan/train.py -opt options/train_realesrnet_x4plus.yml --debug
and ZeroDivisionError produced, 
and i trace the code and find in basicsr/train.py
function create_train_val_dataloader()
            num_iter_per_epoch = math.ceil(
                len(train_set) * dataset_enlarge_ratio / (dataset_opt['batch_size_per_gpu'] * opt['world_size']))

actually  len(train_set)  return 0, however it has value, see picture below
<img width="771" alt="图片" src="https://github.com/xinntao/Real-ESRGAN/assets/129482867/d1b1f941-4e79-4bf2-9acc-1448ee7b7559">

**Comment by XavierPixel** [comment]
还是meta_info_DF2Kmultiscale.txt 访问不到，yml最好改成绝对路径
@DATASET_REGISTRY.register()
class RealESRGANDataset(data.Dataset):

            **with open(self.opt['meta_info']) as fin:**----不太合适
                paths = [line.strip().split(' ')[0] for line in fin]
                self.paths = [os.path.join(self.gt_folder, v) for v in paths]

**Comment by yizhiqianxing** [comment]
Hello, I also encountered the same problem, can you share your modified code
