### ISSUE TITLE
KeyError: "No object named 'RealESRGANDataset' found in 'dataset' registry!"

### ISSUE THREAD

**Issue by Jimzhou82sub** [xinntao/Real-ESRGAN#74]

**Comment by KleinXin** [comment]
Same question

**Comment by KleinXin** [comment]
> 同学你这个问题是怎么解决的呢？

1. mv realesrgan/train.py ../
2. change line 14 of train.py to root_path = osp.abspath(osp.join(__file__, osp.pardir))
3. python train.py xxx

**Comment by Jimzhou82sub** [comment]
cool,

**Comment by CXDprint** [comment]
Same question，but no sloved，please help me

**Comment by CXDprint** [comment]
same question，but not sloved，please detailed tops
