### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by ahmadsakir** [xinntao/Real-ESRGAN#816]
![Screenshot 2024-06-23 153754](https://github.com/xinntao/Real-ESRGAN/assets/40929272/735bd9e5-7cd5-4206-abd2-212f1287628e)

**Comment by liyukun-mathmagic** [comment]
how to fix this bug？

**Comment by Mik3Qiao** [comment]
> how to fix this bug？

This worked for me, using pycharm 2024
if you replace this line
from: `from torchvision.transforms.functional_tensor import rgb_to_grayscale`
to `from torchvision.transforms.functional import rgb_to_grayscale`
the code will be working again

**Comment by JavierOrtunoRoig** [comment]
> > how to fix this bug？
> 
> This worked for me, using pycharm 2024 if you replace this line from: `from torchvision.transforms.functional_tensor import rgb_to_grayscale` to `from torchvision.transforms.functional import rgb_to_grayscale` the code will be working again

This also works in VSCode
