### ISSUE TITLE
Can't download pretrained weight

### ISSUE THREAD

**Issue by Rongcong28** [xinntao/Real-ESRGAN#84]
I try to run the Colab Demo, but it raises an error 403 forbidden, and then i try to download straight the pretrained weight through https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth and an error like in my screenshot, anyone can help me? please
![image](https://user-images.githubusercontent.com/71493198/134113299-ed916f25-dde3-42fb-b5f0-11dc0da6b6a4.png)

**Comment by xinntao** [comment]
It may be due to the GitHub issue. It is OK now.
