### ISSUE TITLE
Request an application for Android

### ISSUE THREAD

**Issue by tumuyan** [xinntao/Real-ESRGAN#86]
I have tried this software in Windows environment and it works great. Thank you very much for your work.
But as we know,  people prefer to use smart phones to take photos, share and download pictures. It would be more convenient to use smart phones to process pictures.

So can you provide an app for Android system?

**Comment by xinntao** [comment]
Sorry that I am not familiar with Android system. And we may not provide some app :-|

**Comment by tumuyan** [comment]
Does the package for Ubuntu work in others Linux? (for example debian?） or Arm CPU？

I have download the release package for Ubuntu, unzip and move it to my Android derive.

When I run the command `./realesrgan-ncnn-vulkan -i input.jpg -o output.png` , the terminal shows permission denied.

The debian for Android also shows this error.

![IMG_20210923_174535.jpg](https://user-images.githubusercontent.com/3126801/134486843-9b856912-3700-49b0-a8ec-10cf61e2fdbe.jpg)

![Screenshot_2021-09-23-18-18-01-928_com.cuntubuntu.jpg](https://user-images.githubusercontent.com/3126801/134491274-05d7f4c1-ff76-4e06-9453-7cd5ebd7f902.jpg)

**Comment by JustHumanz** [comment]
I think it's impossible to run it on android because `realesrgan-ncnn-vulkan` was compiled in the `x86-64` processor
![Screenshot from 2021-09-23 18-50-09](https://user-images.githubusercontent.com/43176061/134502111-6100174f-c8b8-4940-a40c-807b3f24dc06.png)

**Comment by tumuyan** [comment]
I hava build a Android CLI version and it works well. It support  both realsr and realesr-gan model. 
You need to have experience with the console to use it, so technical support is not available at this time.
I will try to make an APK and release it later.

Note: The input parameter for the model is the path to the folder where the model is located, not the model file. The folder must be named starting with "models-DF2K" and the model must be named 'x4'.
[arm64-v8a.zip](https://github.com/xinntao/Real-ESRGAN/files/8010064/arm64-v8a.zip)

![image](https://user-images.githubusercontent.com/3126801/152677781-474bfa11-f61a-4a14-b2c6-ec1341fbbb7f.png)


models:  链接: https://pan.baidu.com/s/1cQZyeRSDCghUnkvvtaVKDg?pwd=1ymv

**Comment by tumuyan** [comment]
Now I have build the real-esrgan application for Android

https://github.com/tumuyan/RealSR-NCNN-Android/
