### ISSUE TITLE
possibility for a x2 model?

### ISSUE THREAD

**Issue by bycloudai** [xinntao/Real-ESRGAN#9]
Thank you for your amazing work!

Would you be able to provide us with a x2 model? Or is it current not possible?

**Comment by xinntao** [comment]
Hi @bycloudai 
I will upload the X2 and X1 model later~ will let you know when it is uploaded. Thanks~

**Comment by Timliuzhaolu** [comment]
> 

Hi @xinntao, I noticed that the X2 model was uploaded however I cannot find the X1 model. Has that also been uploaded somewhere? Thanks a lot!
