### ISSUE TITLE
Can it run on cpu

### ISSUE THREAD

**Issue by djkcyl** [xinntao/Real-ESRGAN#91]
how to run on Ubuntu server with only cpu

**Comment by BearNinja123** [comment]
I don't see why you would (it would take months to train a model with only CPUs), but in ```realesrgan/models```, there are two model scripts (```realesrgan_model.py``` and ```realesrnet_model.py```), delete all instances of .cuda in those scripts (e.g. replace ```self.jpeger = DiffJPEG(differentiable=False).cuda()``` to ```self.jpeger = DiffJPEG(differentiable=False)```), and it should run (it ran for me).

**Comment by xinntao** [comment]
1. For the inference, it can be run on CPU
2. For the training, as @BearNinja123  suggests, it is not recommend to train it on CPU.

**Comment by djkcyl** [comment]
ok thx
