### ISSUE TITLE
How to set differenet lr for differenet layers of rrdb?

### ISSUE THREAD

**Issue by splinter21** [xinntao/Real-ESRGAN#99]
Do I need change the basicsr code?

**Comment by xinntao** [comment]
No, you can set different learning rates in this repo.

You can set here: https://github.com/xinntao/Real-ESRGAN/blob/master/realesrgan/models/realesrgan_model.py

In the `RealESRGANModel` class, create a function named `setup_optimizers`. 
The function can be like this:
https://github.com/xinntao/BasicSR/blob/4f2e81dca6ef7682fe168fb69effb104209be38e/basicsr/models/edvr_model.py#L18-L48
